import rtconfig
Import('RTT_ROOT')
from building import *

src_bsp = ['board.c', 'stm32f10x_it.c']
src_drv = ['rtc.c', 'usart.c', 'led.c']

usb_drv = Split("""
usb/hw_config.c
usb/usb_desc.c
usb/usb_istr.c
usb/usb_prop.c
usb/usb_pwr.c
usb/cdc_serial.c
""")

if GetDepend('RT_USING_DFS'):
	if rtconfig.STM32_TYPE == 'STM32F10X_HD':
		src_drv += ['sdcard.c']
	else:
		src_drv += ['msd.c']

if GetDepend('RT_USING_LWIP'):
	src_drv += ['enc28j60.c'] + ['dm9000a.c']

if GetDepend('RT_USING_RTGUI'):
    src_drv += ['touch.c']

if GetDepend('RT_USING_RTGUI'):
	if rtconfig.RT_USING_LCD_TYPE == 'FMT0371':
		src_drv += ['lcd_a70.c']
	elif rtconfig.RT_USING_LCD_TYPE == 'ILI932X':
		src_drv += ['ili_lcd_general.c']
	elif rtconfig.RT_USING_LCD_TYPE == 'SSD1289':
		src_drv += ['ssd1289.c']

src = src_bsp + src_drv
path = [ GetCurrentDir() ]

if GetDepend('RT_USING_STD_USB'):
    src += usb_drv
    path += [GetCurrentDir() + '/usb']

CPPDEFINES = []
group = DefineGroup('Startup', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
